### ISSUE TITLE
Cannot load PDF file that contains non-ascii characters in file path on Windows

### ISSUE THREAD

**Issue by khanhtd36** [mara004/pypdfium-reboot#1]
OS: Windows 10 x64 21H1 (build 19043.1288)
Python: CPython 3.6.8 x64
Library version: pypdfium-reboot==0.27.0

Input pdf file path that contains non-ascii character (eg. tênfilechứakýtựđặcbiệt.pdf) cannot be read by the library.

```python
doc = pdfium.FPDF_LoadDocument('tênfilechứakýtựnonasscii.pdf', None)
page_count = pdfium.FPDF_GetPageCount(doc)  # page_count = 0 !?
```

**Comment by mara004** [comment]
> page_count = pdfium.FPDF_GetPageCount(doc)  # page_count = 0 !?

Is page count being 0 the only issue that you are experiencing? If so, your problem might be unrelated to the non-ascii filename and rather be caused an issue with the document itself.

**Comment by mara004** [comment]
See [pypdfium2 # known limitations](https://github.com/pypdfium2-team/pypdfium2#known-limitations).
